// src/services/story/map-definitions/act-2-map-definition.ts - Definición visual editable del acto 2 del mapa Story.
import { IStoryActMapDefinition } from "@/services/story/map-definitions/story-map-definition-types";

/**
 * Acto 2 con ramas largas y convergencia previa al boss final.
 */
export const storyAct2MapDefinition: IStoryActMapDefinition = {
  act: 2,
  nodes: [
    {
      id: "story-ch2-duel-1",
      unlockRequirementNodeId: "story-ch1-duel-3",
      position: { x: 860, y: 500 },
    },
    {
      id: "story-ch2-duel-2",
      unlockRequirementNodeId: "story-ch2-hub-omega-alpha",
      pathLinkFromNodeIds: ["story-ch2-hub-omega-beta"],
      position: { x: 1120, y: 210 },
    },
  ],
  virtualNodes: [
    {
      id: "story-ch2-event-signal",
      chapter: 2,
      duelIndex: 201,
      nodeType: "EVENT",
      title: "Señal Fantasma",
      opponentName: "Tráfico encriptado",
      difficulty: "STANDARD",
      rewardNexus: 0,
      rewardPlayerExperience: 0,
      isBossDuel: false,
      unlockRequirementNodeId: "story-ch2-duel-1",
      href: "#",
      position: { x: 620, y: 430 },
    },
    {
      id: "story-ch2-event-signal-2",
      chapter: 2,
      duelIndex: 202,
      nodeType: "EVENT",
      title: "Eco de Firewall",
      opponentName: "Canal hostil",
      difficulty: "STANDARD",
      rewardNexus: 0,
      rewardPlayerExperience: 0,
      isBossDuel: false,
      unlockRequirementNodeId: "story-ch2-event-signal",
      href: "#",
      position: { x: 540, y: 340 },
    },
    {
      id: "story-ch2-reward-card",
      chapter: 2,
      duelIndex: 203,
      nodeType: "REWARD_CARD",
      title: "Alijo de Carta",
      opponentName: "Contenedor seguro",
      difficulty: "STANDARD",
      rewardNexus: 0,
      rewardPlayerExperience: 120,
      isBossDuel: false,
      unlockRequirementNodeId: "story-ch2-event-signal-2",
      href: "#",
      position: { x: 650, y: 250 },
    },
    {
      id: "story-ch2-hub-omega-alpha",
      chapter: 2,
      duelIndex: 204,
      nodeType: "EVENT",
      title: "Hub Omega Alpha",
      opponentName: "Router central",
      difficulty: "ELITE",
      rewardNexus: 0,
      rewardPlayerExperience: 50,
      isBossDuel: false,
      unlockRequirementNodeId: "story-ch2-reward-card",
      href: "#",
      position: { x: 920, y: 250 },
    },
    {
      id: "story-ch2-event-breach",
      chapter: 2,
      duelIndex: 205,
      nodeType: "EVENT",
      title: "Brecha Lateral",
      opponentName: "Canal de ataque",
      difficulty: "STANDARD",
      rewardNexus: 0,
      rewardPlayerExperience: 0,
      isBossDuel: false,
      unlockRequirementNodeId: "story-ch2-duel-1",
      href: "#",
      position: { x: 1240, y: 430 },
    },
    {
      id: "story-ch2-reward-nexus",
      chapter: 2,
      duelIndex: 206,
      nodeType: "REWARD_NEXUS",
      title: "Contador Nexus",
      opponentName: "Tesorería",
      difficulty: "STANDARD",
      rewardNexus: 260,
      rewardPlayerExperience: 0,
      isBossDuel: false,
      unlockRequirementNodeId: "story-ch2-event-breach",
      href: "#",
      position: { x: 1360, y: 340 },
    },
    {
      id: "story-ch2-event-breach-2",
      chapter: 2,
      duelIndex: 207,
      nodeType: "EVENT",
      title: "Pulso Inverso",
      opponentName: "Nodo espejo",
      difficulty: "ELITE",
      rewardNexus: 0,
      rewardPlayerExperience: 0,
      isBossDuel: false,
      unlockRequirementNodeId: "story-ch2-reward-nexus",
      href: "#",
      position: { x: 1270, y: 250 },
    },
    {
      id: "story-ch2-hub-omega-beta",
      chapter: 2,
      duelIndex: 208,
      nodeType: "EVENT",
      title: "Hub Omega Beta",
      opponentName: "Router central",
      difficulty: "ELITE",
      rewardNexus: 0,
      rewardPlayerExperience: 50,
      isBossDuel: false,
      unlockRequirementNodeId: "story-ch2-event-breach-2",
      href: "#",
      position: { x: 1080, y: 250 },
      pathLinkFromNodeIds: ["story-ch2-hub-omega-alpha"],
    },
  ],
  platforms: [
    { id: "act2-platform-1", position: { x: 840, y: 560 }, size: 180, rotationDeg: -6, style: "METAL" },
    { id: "act2-platform-2", position: { x: 620, y: 300 }, size: 170, style: "NEON" },
    { id: "act2-platform-3", position: { x: 1360, y: 300 }, size: 170, style: "RUIN" },
    { id: "act2-platform-4", position: { x: 1000, y: 280 }, size: 210, style: "NEON" },
  ],
};
