// src/services/story/map-definitions/act-1-map-definition.ts - Definición visual editable del acto 1 del mapa Story.
import { IStoryActMapDefinition } from "@/services/story/map-definitions/story-map-definition-types";

/**
 * Acto 1 con rutas laterales y reencuentros visuales antes del jefe.
 */
export const storyAct1MapDefinition: IStoryActMapDefinition = {
  act: 1,
  nodes: [
    { id: "story-ch1-duel-1", unlockRequirementNodeId: "story-ch1-player-start", position: { x: 1000, y: 1540 } },
    {
      id: "story-ch1-duel-2",
      unlockRequirementNodeId: "story-ch1-hub-rejoin-alpha",
      pathLinkFromNodeIds: ["story-ch1-hub-rejoin-beta"],
      position: { x: 1000, y: 1040 },
    },
    { id: "story-ch1-duel-3", unlockRequirementNodeId: "story-ch1-duel-2", position: { x: 1000, y: 700 } },
  ],
  virtualNodes: [
    {
      id: "story-ch1-player-start",
      chapter: 1,
      duelIndex: 90,
      nodeType: "MOVE",
      title: "Plataforma de Inserción",
      opponentName: "Jugador",
      difficulty: "ROOKIE",
      rewardNexus: 0,
      rewardPlayerExperience: 0,
      isBossDuel: false,
      unlockRequirementNodeId: null,
      href: "#",
      position: { x: 1000, y: 1760 },
    },
    {
      id: "story-ch1-event-briefing",
      chapter: 1,
      duelIndex: 101,
      nodeType: "EVENT",
      title: "Terminal de Briefing",
      opponentName: "Canal de Mando",
      difficulty: "ROOKIE",
      rewardNexus: 0,
      rewardPlayerExperience: 0,
      isBossDuel: false,
      unlockRequirementNodeId: "story-ch1-duel-1",
      href: "#",
      position: { x: 720, y: 1360 },
    },
    {
      id: "story-ch1-event-scout-a",
      chapter: 1,
      duelIndex: 102,
      nodeType: "EVENT",
      title: "Nodo de Rastreo",
      opponentName: "Sensor lateral",
      difficulty: "ROOKIE",
      rewardNexus: 0,
      rewardPlayerExperience: 0,
      isBossDuel: false,
      unlockRequirementNodeId: "story-ch1-event-briefing",
      href: "#",
      position: { x: 640, y: 1210 },
    },
    {
      id: "story-ch1-reward-cache-a",
      chapter: 1,
      duelIndex: 103,
      nodeType: "REWARD_NEXUS",
      title: "Cache A",
      opponentName: "Nodo de Recompensa",
      difficulty: "ROOKIE",
      rewardNexus: 120,
      rewardPlayerExperience: 0,
      isBossDuel: false,
      unlockRequirementNodeId: "story-ch1-event-scout-a",
      href: "#",
      position: { x: 760, y: 1060 },
    },
    {
      id: "story-ch1-hub-rejoin-alpha",
      chapter: 1,
      duelIndex: 104,
      nodeType: "EVENT",
      title: "Hub Alpha",
      opponentName: "Enlace troncal",
      difficulty: "STANDARD",
      rewardNexus: 0,
      rewardPlayerExperience: 30,
      isBossDuel: false,
      unlockRequirementNodeId: "story-ch1-reward-cache-a",
      href: "#",
      position: { x: 920, y: 980 },
    },
    {
      id: "story-ch1-event-market",
      chapter: 1,
      duelIndex: 105,
      nodeType: "EVENT",
      title: "Puerto Negro",
      opponentName: "Tráfico de mercado",
      difficulty: "ROOKIE",
      rewardNexus: 0,
      rewardPlayerExperience: 0,
      isBossDuel: false,
      unlockRequirementNodeId: "story-ch1-duel-1",
      href: "#",
      position: { x: 1280, y: 1360 },
    },
    {
      id: "story-ch1-reward-card-beta",
      chapter: 1,
      duelIndex: 106,
      nodeType: "REWARD_CARD",
      title: "Bóveda Beta",
      opponentName: "Contenedor seguro",
      difficulty: "ROOKIE",
      rewardNexus: 0,
      rewardPlayerExperience: 80,
      isBossDuel: false,
      unlockRequirementNodeId: "story-ch1-event-market",
      href: "#",
      position: { x: 1380, y: 1210 },
    },
    {
      id: "story-ch1-event-scout-b",
      chapter: 1,
      duelIndex: 107,
      nodeType: "EVENT",
      title: "Relay B",
      opponentName: "Observatorio",
      difficulty: "STANDARD",
      rewardNexus: 0,
      rewardPlayerExperience: 0,
      isBossDuel: false,
      unlockRequirementNodeId: "story-ch1-reward-card-beta",
      href: "#",
      position: { x: 1260, y: 1060 },
    },
    {
      id: "story-ch1-hub-rejoin-beta",
      chapter: 1,
      duelIndex: 108,
      nodeType: "EVENT",
      title: "Hub Beta",
      opponentName: "Enlace troncal",
      difficulty: "STANDARD",
      rewardNexus: 0,
      rewardPlayerExperience: 30,
      isBossDuel: false,
      unlockRequirementNodeId: "story-ch1-event-scout-b",
      href: "#",
      position: { x: 1080, y: 980 },
      pathLinkFromNodeIds: ["story-ch1-hub-rejoin-alpha"],
    },
  ],
  platforms: [
    { id: "act1-platform-start", position: { x: 1000, y: 1820 }, size: 210, style: "NEON" },
    { id: "act1-platform-1", position: { x: 860, y: 1660 }, size: 150, rotationDeg: -14, style: "METAL" },
    { id: "act1-platform-2", position: { x: 1160, y: 1660 }, size: 140, rotationDeg: 12, style: "RUIN" },
    { id: "act1-platform-3", position: { x: 660, y: 1270 }, size: 170, rotationDeg: 8, style: "NEON" },
    { id: "act1-platform-4", position: { x: 1360, y: 1270 }, size: 175, rotationDeg: -7, style: "METAL" },
    { id: "act1-platform-5", position: { x: 980, y: 1120 }, size: 220, style: "RUIN" },
  ],
};
