// src/components/game/board/ui/overlays/internal/board-status-overlays.types.ts - Contrato de propiedades del contenedor de overlays del tablero.
import { ICard } from "@/core/entities/ICard";
import { ICombatLogEvent } from "@/core/entities/ICombatLog";
import { IBoardUiError } from "../../../hooks/internal/boardError";
import { IPendingZoneReplacement } from "../../../hooks/internal/board-state/pending-replacement";
import { ITrapActivationPrompt } from "../../../hooks/internal/board-state/useBoardUiState";
import { IBattleBannerMessage } from "../../internal/banner/banner-message-policy";
import { IFusionMaterialCandidate } from "./FusionMaterialBrowser";

export interface BoardStatusOverlaysProps {
  lastError: IBoardUiError | null;
  pendingActionHint: string | null;
  pendingTrapActivationPrompt?: ITrapActivationPrompt | null;
  pendingEntityReplacement: IPendingZoneReplacement | null;
  pendingEntityReplacementTargetCard: ICard | null;
  combatLog: ICombatLogEvent[];
  playerAId: string;
  playerAName: string;
  playerBId: string;
  playerBName: string;
  isPaused: boolean;
  onResumePause: () => void;
  onExitPause?: () => void;
  isFusionCinematicActive?: boolean;
  setIsFusionCinematicActive?: (value: boolean) => void;
  graveyardView: "player" | "opponent" | null;
  graveyardOwnerName: string;
  graveyardCards: ICard[];
  graveyardSelectableCardRefs?: string[];
  fusionDeckView?: "player" | "opponent" | null;
  fusionDeckOwnerName?: string;
  fusionDeckCards?: ICard[];
  destroyedView?: "player" | "opponent" | null;
  destroyedOwnerName?: string;
  destroyedCards?: ICard[];
  onCloseError: () => void;
  onConfirmEntityReplacement: () => void;
  onCancelEntityReplacement: () => void;
  onCloseGraveyard: () => void;
  onCloseFusionDeck?: () => void;
  onCloseDestroyed?: () => void;
  onPreviewCard: (card: ICard) => void;
  pendingAdvanceWarning: "MAIN_SKIP_ACTIONS" | "BATTLE_SKIP_ATTACKS" | null;
  onConfirmAdvancePhase: (disableHelp: boolean) => void;
  onCancelAdvancePhase: () => void;
  externalBannerSignal?: IBattleBannerMessage | null;
  showBattleBanners?: boolean;
  isFusionMaterialBrowserOpen?: boolean;
  fusionMaterialCandidates?: IFusionMaterialCandidate[];
  fusionSelectedCount?: number;
  onSelectFusionMaterial?: (instanceId: string) => void;
}
