// src/services/tutorial/combat/internal/combat-tutorial-endgame-steps.ts - Bloque final del tutorial con cementerio, cierre de combate y lectura de recompensas.
import { ITutorialFlowStep } from "@/core/entities/tutorial/ITutorialFlowStep";

export const COMBAT_TUTORIAL_ENDGAME_STEPS: ITutorialFlowStep[] = [
  { id: "combat-select-python", title: "Robo de Python", description: "En tu siguiente turno roba y selecciona Python para mostrar ataque contra defensa.", targetId: "tutorial-board-hand-card-entity-python", allowedTargetIds: ["tutorial-board-hand-card-entity-python"], completionType: "USER_ACTION", expectedActionId: "SELECT_PYTHON" },
  { id: "combat-summon-python", title: "Invoca Python", description: "Invoca Python en ataque para preparar la secuencia final.", targetId: "tutorial-board-action-attack", allowedTargetIds: ["tutorial-board-action-attack", "tutorial-board-hand-card-entity-python"], completionType: "USER_ACTION", expectedActionId: "SUMMON_PYTHON_ATTACK" },
  { id: "combat-graveyard-open", title: "Cementerio", description: "Pulsa el contenedor de cementerio para abrirlo y revisar las cartas enviadas.", targetId: "tutorial-board-graveyard-player", allowedTargetIds: ["tutorial-board-graveyard-player"], completionType: "USER_ACTION", expectedActionId: "OPEN_GRAVEYARD" },
  { id: "combat-graveyard-explained", title: "Información del cementerio", description: "Aquí puedes consultar cartas descartadas o destruidas y sus detalles.", targetId: "tutorial-board-graveyard-browser", allowedTargetIds: [], completionType: "MANUAL_NEXT" },
  { id: "combat-graveyard-close", title: "Cerrar cementerio", description: "Cierra el cementerio para volver al campo y continuar el turno.", targetId: "tutorial-board-graveyard-close", allowedTargetIds: ["tutorial-board-graveyard-close"], completionType: "USER_ACTION", expectedActionId: "CLOSE_GRAVEYARD" },
  { id: "combat-python-battle-phase", title: "Entrar en Combate", description: "Pulsa Combate para resolver ataque a carta en defensa y cierre del duelo.", targetId: "tutorial-board-phase-battle-button", allowedTargetIds: ["tutorial-board-phase-controls", "tutorial-board-phase-battle-button"], completionType: "USER_ACTION", expectedActionId: "TURN_TO_BATTLE_PYTHON" },
  { id: "combat-fusion-defense-attack", title: "Primero: fusión contra defensa", description: "Ataca con GemGPT a la entidad rival en defensa. En defensa no bajas LP, pero sí puedes destruir su carta.", targetId: "tutorial-board-player-entity-card-fusion-gemgpt", allowedTargetIds: ["tutorial-board-battlefield", "tutorial-board-player-entity-card-fusion-gemgpt"], completionType: "USER_ACTION", expectedActionId: "FUSION_ATTACK_DEFENSE_DONE" },
  { id: "combat-python-direct-attack-final", title: "Segundo: ataque directo con Python", description: "Ahora sí: con el campo rival limpio, ataca directo con Python para cerrar el combate.", targetId: "tutorial-board-player-entity-card-entity-python", allowedTargetIds: ["tutorial-board-battlefield", "tutorial-board-player-entity-card-entity-python", "tutorial-board-opponent-zone-1"], completionType: "USER_ACTION", expectedActionId: "PYTHON_DIRECT_ATTACK_DONE" },
  { id: "combat-win-confirmed", title: "Combate ganado", description: "Perfecto. Esta secuencia demuestra la diferencia entre atacar defensa y atacar directo a LP.", targetId: "tutorial-board-battlefield", allowedTargetIds: ["tutorial-board-battlefield"], completionType: "USER_ACTION", expectedActionId: "MATCH_WON" },
  { id: "combat-result-overview", title: "Resumen final", description: "Al terminar el duelo aparece este panel con el resultado y el resumen de progreso.", targetId: "tutorial-board-duel-result-overlay", allowedTargetIds: [], completionType: "MANUAL_NEXT" },
  { id: "combat-result-experience", title: "Experiencia", description: "Aquí verás la experiencia de tus cartas por acciones del combate (invocar, activar efectos, destruir o atacar).", targetId: "tutorial-board-duel-result-experience", allowedTargetIds: [], completionType: "MANUAL_NEXT" },
  { id: "combat-result-rewards", title: "Nexus y regalo", description: "En modos con recompensa también verás EXP de jugador, Nexus y, si toca drop, una carta regalo.", targetId: "tutorial-board-duel-result-rewards", allowedTargetIds: [], completionType: "MANUAL_NEXT" },
  { id: "combat-result-next-steps", title: "Continuar", description: "Usa el botón final para volver y seguir con el siguiente nodo del tutorial.", targetId: "tutorial-board-duel-result-overlay", allowedTargetIds: [], completionType: "MANUAL_NEXT" },
];
