// src/services/tutorial/combat/internal/combat-tutorial-opening-steps.ts - Bloque de apertura con invocación inicial, buff, trampa y cambio de subturnos.
import { ITutorialFlowStep } from "@/core/entities/tutorial/ITutorialFlowStep";

export const COMBAT_TUTORIAL_OPENING_STEPS: ITutorialFlowStep[] = [
  { id: "combat-select-chatgpt", title: "Selecciona ChatGPT", description: "Selecciona ChatGPT en mano para desplegar acciones de invocación.", targetId: "tutorial-board-hand-card-entity-chatgpt", allowedTargetIds: ["tutorial-board-hand-card-entity-chatgpt"], completionType: "USER_ACTION", expectedActionId: "SELECT_CHATGPT" },
  { id: "combat-summon-chatgpt-attack", title: "Invoca en ataque", description: "Invoca ChatGPT en ATTACK para iniciar presión ofensiva.", targetId: "tutorial-board-action-attack", allowedTargetIds: ["tutorial-board-hand-card-entity-chatgpt", "tutorial-board-action-attack"], completionType: "USER_ACTION", expectedActionId: "SUMMON_CHATGPT_ATTACK" },
  { id: "combat-select-boost", title: "Selecciona mágica +400", description: "Selecciona la mágica de +400 ATK para potenciar tu entidad activa.", targetId: "tutorial-board-hand-card-exec-boost-atk-400", allowedTargetIds: ["tutorial-board-hand-card-exec-boost-atk-400"], completionType: "USER_ACTION", expectedActionId: "SELECT_BOOST_EXECUTION" },
  { id: "combat-activate-boost", title: "Activa la mágica", description: "Activa la ejecución y observa la mejora de ataque en tu entidad.", targetId: "tutorial-board-action-activate-execution", allowedTargetIds: ["tutorial-board-action-activate-execution", "tutorial-board-hand-card-exec-boost-atk-400"], completionType: "USER_ACTION", expectedActionId: "ACTIVATE_BOOST_EXECUTION" },
  { id: "combat-boost-result", title: "Resultado del buff", description: "La mágica ya aplicó el +400 ATQ. Fíjate en el valor actualizado antes de continuar.", targetId: "tutorial-board-battlefield", allowedTargetIds: [], completionType: "MANUAL_NEXT" },
  { id: "combat-select-trap", title: "Selecciona la trampa", description: "Ahora selecciona la trampa para dejar defensa reactiva en mesa.", targetId: "tutorial-board-hand-card-tutorial-trap-attack-drain-200", allowedTargetIds: ["tutorial-board-hand-card-tutorial-trap-attack-drain-200"], completionType: "USER_ACTION", expectedActionId: "SELECT_TUTORIAL_TRAP" },
  { id: "combat-set-trap", title: "Set de trampa", description: "Coloca la trampa en SET para que se active al ataque rival.", targetId: "tutorial-board-action-set-trap", allowedTargetIds: ["tutorial-board-action-set-trap", "tutorial-board-hand-card-tutorial-trap-attack-drain-200"], completionType: "USER_ACTION", expectedActionId: "SET_TUTORIAL_TRAP" },
  { id: "combat-subturns-battle", title: "Subturnos", description: "Invocar sirve para jugar cartas. Pulsa Combate para entrar en la fase de ataques.", targetId: "tutorial-board-phase-battle-button", allowedTargetIds: ["tutorial-board-phase-controls", "tutorial-board-phase-battle-button"], completionType: "USER_ACTION", expectedActionId: "TURN_TO_BATTLE" },
  { id: "combat-subturns-pass", title: "Subturnos", description: "Ahora pulsa Pasar para cerrar el turno y cederlo al rival.", targetId: "tutorial-board-phase-pass-button", allowedTargetIds: ["tutorial-board-phase-controls", "tutorial-board-phase-pass-button"], completionType: "USER_ACTION", expectedActionId: "TURN_PASSED_TO_OPPONENT" },
];
