// src/services/tutorial/combat/internal/combat-tutorial-midgame-steps.ts - Bloque medio del combate con respuesta rival, gestión de energía y ataques directos.
import { ITutorialFlowStep } from "@/core/entities/tutorial/ITutorialFlowStep";

export const COMBAT_TUTORIAL_MIDGAME_STEPS: ITutorialFlowStep[] = [
  { id: "combat-opponent-trap-prompt", title: "Decisión de trampa", description: "Cuando el rival declara ataque, aparece un prompt de trampa. En este tutorial, pulsa Activar para responder.", targetId: "tutorial-board-action-activate-trap-prompt", allowedTargetIds: ["tutorial-board-action-activate-trap-prompt"], completionType: "USER_ACTION", expectedActionId: "TRAP_PROMPT_VISIBLE" },
  { id: "combat-opponent-trap-resolution", title: "Turno rival y trampa", description: "Con la decisión confirmada, tu trampa reduce ATK y el atacante rival termina destruido.", targetId: "tutorial-board-battlefield", allowedTargetIds: ["tutorial-board-battlefield", "tutorial-board-action-activate-trap-prompt"], completionType: "USER_ACTION", expectedActionId: "TRAP_DEFENSE_RESOLVED" },
  { id: "combat-opponent-trap-explained", title: "Qué pasó en la batalla", description: "La trampa restó 200 ATQ al atacante rival; por eso tu entidad ganó ese choque.", targetId: "tutorial-board-battlefield", allowedTargetIds: [], completionType: "MANUAL_NEXT" },
  { id: "combat-opponent-set", title: "Set del rival", description: "El rival también puede dejar cartas en SET en su zona de ejecución/trampa.", targetId: "tutorial-board-battlefield", allowedTargetIds: ["tutorial-board-battlefield"], completionType: "MANUAL_NEXT" },
  { id: "combat-select-energy-restore", title: "Selecciona recarga de energía", description: "Antes de invocar Gemini, usa la ejecución que recupera energía.", targetId: "tutorial-board-hand-card-tutorial-exec-energy-restore", allowedTargetIds: ["tutorial-board-hand-card-tutorial-exec-energy-restore"], completionType: "USER_ACTION", expectedActionId: "SELECT_ENERGY_RESTORE" },
  { id: "combat-activate-energy-restore", title: "Activa recarga", description: "Activa Recarga de Núcleo y recupera energía para seguir el turno.", targetId: "tutorial-board-action-activate-execution", allowedTargetIds: ["tutorial-board-action-activate-execution", "tutorial-board-hand-card-tutorial-exec-energy-restore"], completionType: "USER_ACTION", expectedActionId: "ACTIVATE_ENERGY_RESTORE" },
  { id: "combat-energy-restored", title: "Energía recuperada", description: "Con la energía restaurada, selecciona Gemini para continuar la jugada.", targetId: "tutorial-board-hand-card-entity-gemini", allowedTargetIds: ["tutorial-board-hand-card-entity-gemini"], completionType: "USER_ACTION", expectedActionId: "SELECT_GEMINI" },
  { id: "combat-summon-gemini", title: "Invoca Gemini", description: "Invoca Gemini y usa tus entidades para presión de mesa.", targetId: "tutorial-board-action-attack", allowedTargetIds: ["tutorial-board-action-attack", "tutorial-board-hand-card-entity-gemini"], completionType: "USER_ACTION", expectedActionId: "SUMMON_GEMINI_ATTACK" },
  { id: "combat-direct-attack-enter-battle", title: "Entrar en Combate", description: "Primero pulsa el botón Combate para pasar de Invocar a fase de batalla.", targetId: "tutorial-board-phase-battle-button", allowedTargetIds: ["tutorial-board-phase-controls", "tutorial-board-phase-battle-button"], completionType: "USER_ACTION", expectedActionId: "TURN_TO_BATTLE_FOR_DIRECT_ATTACK" },
  { id: "combat-direct-attack-guide", title: "Ataca directo", description: "No hay entidades rivales en mesa: puedes atacar directo. Primero selecciona ChatGPT.", targetId: "tutorial-board-player-entity-card-entity-chatgpt", allowedTargetIds: ["tutorial-board-phase-controls", "tutorial-board-battlefield", "tutorial-board-player-entity-card-entity-chatgpt"], completionType: "USER_ACTION", expectedActionId: "SELECT_CHATGPT_BOARD_ATTACK" },
  { id: "combat-direct-attack-chatgpt", title: "Ataca con ChatGPT", description: "Con ChatGPT seleccionado, toca una zona rival resaltada para declarar ataque directo.", targetId: "tutorial-board-opponent-zone-1", allowedTargetIds: ["tutorial-board-opponent-zone-1"], completionType: "USER_ACTION", expectedActionId: "PLAYER_DIRECT_ATTACK_1_DONE" },
  { id: "combat-direct-attack-gemini-select", title: "Segundo atacante", description: "Ahora selecciona Gemini para repetir el ataque directo.", targetId: "tutorial-board-player-entity-card-entity-gemini", allowedTargetIds: ["tutorial-board-battlefield", "tutorial-board-player-entity-card-entity-gemini"], completionType: "USER_ACTION", expectedActionId: "SELECT_GEMINI_BOARD_ATTACK" },
  { id: "combat-direct-attack-gemini", title: "Ataca con Gemini", description: "Con Gemini seleccionado, toca de nuevo la zona rival resaltada para el segundo ataque directo.", targetId: "tutorial-board-opponent-zone-1", allowedTargetIds: ["tutorial-board-opponent-zone-1"], completionType: "USER_ACTION", expectedActionId: "PLAYER_DIRECT_ATTACK_2_DONE" },
  { id: "combat-direct-attack-explained", title: "Daño directo", description: "Perfecto. Cuando el rival no tiene entidades, tus ataques van directamente a sus LP.", targetId: "tutorial-board-battlefield", allowedTargetIds: [], completionType: "MANUAL_NEXT" },
  { id: "combat-pass-opponent-set", title: "Ceder turno", description: "Pulsa Pasar: el rival pondrá una carta en SET para preparar su defensa.", targetId: "tutorial-board-phase-pass-button", allowedTargetIds: ["tutorial-board-phase-controls", "tutorial-board-phase-pass-button"], completionType: "USER_ACTION", expectedActionId: "OPPONENT_SET_DONE" },
];
