// src/services/tutorial/combat/internal/combat-tutorial-fusion-steps.ts - Bloque de secuencia de fusión y resolución previa al cierre del duelo.
import { ITutorialFlowStep } from "@/core/entities/tutorial/ITutorialFlowStep";

export const COMBAT_TUTORIAL_FUSION_STEPS: ITutorialFlowStep[] = [
  { id: "combat-select-fusion-magic", title: "Robo clave", description: "Tu siguiente robo es la mágica de fusión. Selecciónala para iniciar la invocación de GemGPT.", targetId: "tutorial-board-hand-card-exec-fusion-gemgpt", allowedTargetIds: ["tutorial-board-hand-card-exec-fusion-gemgpt"], completionType: "USER_ACTION", expectedActionId: "SELECT_FUSION_MAGIC" },
  { id: "combat-activate-fusion-magic", title: "Activa fusión", description: "Activa Fusion Compiler para abrir el selector de materiales.", targetId: "tutorial-board-action-activate-execution", allowedTargetIds: ["tutorial-board-action-activate-execution", "tutorial-board-hand-card-exec-fusion-gemgpt"], completionType: "USER_ACTION", expectedActionId: "FUSION_BROWSER_OPEN" },
  { id: "combat-fusion-material-1", title: "Material 1", description: "Selecciona el primer material de fusión (ChatGPT o Gemini).", targetId: "tutorial-board-fusion-material-entity-chatgpt", allowedTargetIds: ["tutorial-board-fusion-browser", "tutorial-board-fusion-material-entity-chatgpt", "tutorial-board-fusion-material-entity-gemini"], completionType: "USER_ACTION", expectedActionId: "FUSION_MATERIAL_1_SELECTED" },
  { id: "combat-fusion-material-2", title: "Material 2", description: "Ahora selecciona el segundo material para completar la fusión.", targetId: "tutorial-board-fusion-material-entity-gemini", allowedTargetIds: ["tutorial-board-fusion-browser", "tutorial-board-fusion-material-entity-chatgpt", "tutorial-board-fusion-material-entity-gemini"], completionType: "USER_ACTION", expectedActionId: "FUSION_MATERIAL_2_SELECTED" },
  { id: "combat-fusion-summon-animation", title: "Invocación de fusión", description: "Perfecto. Ahora se ejecuta la animación y aparece GemGPT en el campo.", targetId: "tutorial-board-battlefield", allowedTargetIds: [], completionType: "USER_ACTION", expectedActionId: "FUSION_SUMMON" },
  { id: "combat-fusion-battle-phase", title: "Fase de Combate", description: "Ahora pulsa Combate para atacar con tu carta de fusión.", targetId: "tutorial-board-phase-battle-button", allowedTargetIds: ["tutorial-board-phase-controls", "tutorial-board-phase-battle-button"], completionType: "USER_ACTION", expectedActionId: "TURN_TO_BATTLE_AFTER_FUSION" },
  { id: "combat-fusion-select-card", title: "Selecciona GemGPT", description: "Selecciona tu carta de fusión GemGPT para preparar el ataque directo.", targetId: "tutorial-board-player-entity-card-fusion-gemgpt", allowedTargetIds: ["tutorial-board-battlefield", "tutorial-board-player-entity-card-fusion-gemgpt"], completionType: "USER_ACTION", expectedActionId: "SELECT_FUSION_ENTITY_FOR_ATTACK" },
  { id: "combat-fusion-direct-attack", title: "Ataque de GemGPT", description: "Con GemGPT seleccionada, toca la zona rival resaltada para ejecutar el ataque directo.", targetId: "tutorial-board-opponent-zone-1", allowedTargetIds: ["tutorial-board-opponent-zone-1"], completionType: "USER_ACTION", expectedActionId: "PLAYER_FUSION_DIRECT_ATTACK_DONE" },
  { id: "combat-fusion-trap-explained", title: "Trampa rival", description: "Se activó una trampa rival al declarar ataque: te inflige daño directo, pero tu ataque continúa.", targetId: "tutorial-board-battlefield", allowedTargetIds: [], completionType: "MANUAL_NEXT" },
  { id: "combat-fusion-pass-turn", title: "Cerrar turno", description: "Pulsa Pasar para ceder turno. El rival responderá colocando una carta en defensa.", targetId: "tutorial-board-phase-pass-button", allowedTargetIds: ["tutorial-board-phase-controls", "tutorial-board-phase-pass-button"], completionType: "USER_ACTION", expectedActionId: "OPPONENT_DEFENSE_READY" },
];
