// src/services/tutorial/combat/resolve-combat-tutorial-steps.ts - Secuencia guiada del tutorial de combate con foco en UI, turnos, invocación, trampa y fusión.
import { ITutorialFlowStep } from "@/core/entities/tutorial/ITutorialFlowStep";

export function resolveCombatTutorialSteps(): ITutorialFlowStep[] {
  return [
    { id: "combat-ui-history", title: "CombatLog", description: "Aquí revisas todos los eventos de combate en orden cronológico.", targetId: "tutorial-board-history-button", allowedTargetIds: [], completionType: "MANUAL_NEXT" },
    {
      id: "combat-ui-mute",
      title: "Mute",
      description: "Si quieres, puedes usar Mute para silenciar o reactivar música y efectos.",
      targetId: "tutorial-board-mute-button",
      allowedTargetIds: [],
      completionType: "MANUAL_NEXT",
    },
    { id: "combat-ui-auto", title: "Modo automático", description: "Automático acelera fases; en tutorial lo dejamos desactivado para aprender paso a paso.", targetId: "tutorial-board-auto-button", allowedTargetIds: [], completionType: "MANUAL_NEXT" },
    { id: "combat-ui-pause", title: "Pausa y salir", description: "Desde pausa puedes reanudar o salir del combate.", targetId: "tutorial-board-pause-button", allowedTargetIds: [], completionType: "MANUAL_NEXT" },
    { id: "combat-rules", title: "Reglas base", description: "Si empiezas primero no puedes atacar en turno 1. Solo juegas cartas si tienes energía suficiente.", targetId: "tutorial-board-phase-controls", allowedTargetIds: [], completionType: "MANUAL_NEXT" },
    { id: "combat-rules-timer", title: "Temporizador", description: "En combate normal tienes 30 segundos por subturno. Si se agota, el juego avanza al siguiente subturno automáticamente.", targetId: "tutorial-board-turn-timer-panel", allowedTargetIds: [], completionType: "MANUAL_NEXT" },
    { id: "combat-rules-positions", title: "Ataque vs defensa", description: "En defensa no dañas LP rival, pero sí puedes destruir cartas si tu ataque supera su defensa.", targetId: "tutorial-board-battlefield", allowedTargetIds: [], completionType: "MANUAL_NEXT" },

    { id: "combat-select-chatgpt", title: "Selecciona ChatGPT", description: "Selecciona ChatGPT en mano para desplegar acciones de invocación.", targetId: "tutorial-board-hand-card-entity-chatgpt", allowedTargetIds: ["tutorial-board-hand-card-entity-chatgpt"], completionType: "USER_ACTION", expectedActionId: "SELECT_CHATGPT" },
    { id: "combat-summon-chatgpt-attack", title: "Invoca en ataque", description: "Invoca ChatGPT en ATTACK para iniciar presión ofensiva.", targetId: "tutorial-board-action-attack", allowedTargetIds: ["tutorial-board-hand-card-entity-chatgpt", "tutorial-board-action-attack"], completionType: "USER_ACTION", expectedActionId: "SUMMON_CHATGPT_ATTACK" },
    { id: "combat-select-boost", title: "Selecciona mágica +400", description: "Selecciona la mágica de +400 ATK para potenciar tu entidad activa.", targetId: "tutorial-board-hand-card-exec-boost-atk-400", allowedTargetIds: ["tutorial-board-hand-card-exec-boost-atk-400"], completionType: "USER_ACTION", expectedActionId: "SELECT_BOOST_EXECUTION" },
    { id: "combat-activate-boost", title: "Activa la mágica", description: "Activa la ejecución y observa la mejora de ataque en tu entidad.", targetId: "tutorial-board-action-activate-execution", allowedTargetIds: ["tutorial-board-action-activate-execution", "tutorial-board-hand-card-exec-boost-atk-400"], completionType: "USER_ACTION", expectedActionId: "ACTIVATE_BOOST_EXECUTION" },
    { id: "combat-boost-result", title: "Resultado del buff", description: "La mágica ya aplicó el +400 ATQ. Fíjate en el valor actualizado antes de continuar.", targetId: "tutorial-board-battlefield", allowedTargetIds: [], completionType: "MANUAL_NEXT" },
    { id: "combat-select-trap", title: "Selecciona la trampa", description: "Ahora selecciona la trampa para dejar defensa reactiva en mesa.", targetId: "tutorial-board-hand-card-tutorial-trap-attack-drain-200", allowedTargetIds: ["tutorial-board-hand-card-tutorial-trap-attack-drain-200"], completionType: "USER_ACTION", expectedActionId: "SELECT_TUTORIAL_TRAP" },
    { id: "combat-set-trap", title: "Set de trampa", description: "Coloca la trampa en SET para que se active al ataque rival.", targetId: "tutorial-board-action-set-trap", allowedTargetIds: ["tutorial-board-action-set-trap", "tutorial-board-hand-card-tutorial-trap-attack-drain-200"], completionType: "USER_ACTION", expectedActionId: "SET_TUTORIAL_TRAP" },
    {
      id: "combat-subturns-battle",
      title: "Subturnos",
      description: "Invocar sirve para jugar cartas. Pulsa Combate para entrar en la fase de ataques.",
      targetId: "tutorial-board-phase-battle-button",
      allowedTargetIds: ["tutorial-board-phase-controls", "tutorial-board-phase-battle-button"],
      completionType: "USER_ACTION",
      expectedActionId: "TURN_TO_BATTLE",
    },
    {
      id: "combat-subturns-pass",
      title: "Subturnos",
      description: "Ahora pulsa Pasar para cerrar el turno y cederlo al rival.",
      targetId: "tutorial-board-phase-pass-button",
      allowedTargetIds: ["tutorial-board-phase-controls", "tutorial-board-phase-pass-button"],
      completionType: "USER_ACTION",
      expectedActionId: "TURN_PASSED_TO_OPPONENT",
    },

    { id: "combat-opponent-trap-resolution", title: "Turno rival y trampa", description: "El rival ataca, tu trampa reduce ATK y su carta termina destruida.", targetId: "tutorial-board-battlefield", allowedTargetIds: ["tutorial-board-battlefield"], completionType: "USER_ACTION", expectedActionId: "TRAP_DEFENSE_RESOLVED" },
    { id: "combat-opponent-trap-explained", title: "Qué pasó en la batalla", description: "La trampa restó 200 ATQ al atacante rival; por eso tu entidad ganó ese choque.", targetId: "tutorial-board-battlefield", allowedTargetIds: [], completionType: "MANUAL_NEXT" },
    { id: "combat-opponent-set", title: "Set del rival", description: "El rival también puede dejar cartas en SET en su zona de ejecución/trampa.", targetId: "tutorial-board-battlefield", allowedTargetIds: ["tutorial-board-battlefield"], completionType: "MANUAL_NEXT" },

    { id: "combat-select-energy-restore", title: "Selecciona recarga de energía", description: "Antes de invocar Gemini, usa la ejecución que recupera energía.", targetId: "tutorial-board-hand-card-tutorial-exec-energy-restore", allowedTargetIds: ["tutorial-board-hand-card-tutorial-exec-energy-restore"], completionType: "USER_ACTION", expectedActionId: "SELECT_ENERGY_RESTORE" },
    { id: "combat-activate-energy-restore", title: "Activa recarga", description: "Activa Recarga de Núcleo y recupera energía para seguir el turno.", targetId: "tutorial-board-action-activate-execution", allowedTargetIds: ["tutorial-board-action-activate-execution", "tutorial-board-hand-card-tutorial-exec-energy-restore"], completionType: "USER_ACTION", expectedActionId: "ACTIVATE_ENERGY_RESTORE" },
    {
      id: "combat-energy-restored",
      title: "Energía recuperada",
      description: "Con la energía restaurada, selecciona Gemini para continuar la jugada.",
      targetId: "tutorial-board-hand-card-entity-gemini",
      allowedTargetIds: ["tutorial-board-hand-card-entity-gemini"],
      completionType: "USER_ACTION",
      expectedActionId: "SELECT_GEMINI",
    },
    { id: "combat-summon-gemini", title: "Invoca Gemini", description: "Invoca Gemini y usa tus entidades para presión de mesa.", targetId: "tutorial-board-action-attack", allowedTargetIds: ["tutorial-board-action-attack", "tutorial-board-hand-card-entity-gemini"], completionType: "USER_ACTION", expectedActionId: "SUMMON_GEMINI_ATTACK" },
    {
      id: "combat-direct-attack-enter-battle",
      title: "Entrar en Combate",
      description: "Primero pulsa el botón Combate para pasar de Invocar a fase de batalla.",
      targetId: "tutorial-board-phase-battle-button",
      allowedTargetIds: ["tutorial-board-phase-controls", "tutorial-board-phase-battle-button"],
      completionType: "USER_ACTION",
      expectedActionId: "TURN_TO_BATTLE_FOR_DIRECT_ATTACK",
    },
    {
      id: "combat-direct-attack-guide",
      title: "Ataca directo",
      description: "No hay entidades rivales en mesa: puedes atacar directo. Primero selecciona ChatGPT.",
      targetId: "tutorial-board-player-entity-card-entity-chatgpt",
      allowedTargetIds: ["tutorial-board-phase-controls", "tutorial-board-battlefield", "tutorial-board-player-entity-card-entity-chatgpt"],
      completionType: "USER_ACTION",
      expectedActionId: "SELECT_CHATGPT_BOARD_ATTACK",
    },
    {
      id: "combat-direct-attack-chatgpt",
      title: "Ataca con ChatGPT",
      description: "Con ChatGPT seleccionado, toca una zona rival resaltada para declarar ataque directo.",
      targetId: "tutorial-board-opponent-zone-1",
      allowedTargetIds: ["tutorial-board-opponent-zone-1"],
      completionType: "USER_ACTION",
      expectedActionId: "PLAYER_DIRECT_ATTACK_1_DONE",
    },
    {
      id: "combat-direct-attack-gemini-select",
      title: "Segundo atacante",
      description: "Ahora selecciona Gemini para repetir el ataque directo.",
      targetId: "tutorial-board-player-entity-card-entity-gemini",
      allowedTargetIds: ["tutorial-board-battlefield", "tutorial-board-player-entity-card-entity-gemini"],
      completionType: "USER_ACTION",
      expectedActionId: "SELECT_GEMINI_BOARD_ATTACK",
    },
    {
      id: "combat-direct-attack-gemini",
      title: "Ataca con Gemini",
      description: "Con Gemini seleccionado, toca de nuevo la zona rival resaltada para el segundo ataque directo.",
      targetId: "tutorial-board-opponent-zone-1",
      allowedTargetIds: ["tutorial-board-opponent-zone-1"],
      completionType: "USER_ACTION",
      expectedActionId: "PLAYER_DIRECT_ATTACK_2_DONE",
    },
    {
      id: "combat-direct-attack-explained",
      title: "Daño directo",
      description: "Perfecto. Cuando el rival no tiene entidades, tus ataques van directamente a sus LP.",
      targetId: "tutorial-board-phase-battle-button",
      allowedTargetIds: [],
      completionType: "MANUAL_NEXT",
    },
    {
      id: "combat-pass-opponent-set",
      title: "Ceder turno",
      description: "Pulsa Pasar: el rival pondrá una carta en SET para preparar su defensa.",
      targetId: "tutorial-board-phase-pass-button",
      allowedTargetIds: ["tutorial-board-phase-controls", "tutorial-board-phase-pass-button"],
      completionType: "USER_ACTION",
      expectedActionId: "OPPONENT_SET_DONE",
    },
    {
      id: "combat-select-fusion-magic",
      title: "Robo clave",
      description: "Tu siguiente robo es la mágica de fusión. Selecciónala para iniciar la invocación de GemGPT.",
      targetId: "tutorial-board-hand-card-exec-fusion-gemgpt",
      allowedTargetIds: ["tutorial-board-hand-card-exec-fusion-gemgpt"],
      completionType: "USER_ACTION",
      expectedActionId: "SELECT_FUSION_MAGIC",
    },
    {
      id: "combat-activate-fusion-magic",
      title: "Activa fusión",
      description: "Activa Fusion Compiler para abrir el selector de materiales.",
      targetId: "tutorial-board-action-activate-execution",
      allowedTargetIds: ["tutorial-board-action-activate-execution", "tutorial-board-hand-card-exec-fusion-gemgpt"],
      completionType: "USER_ACTION",
      expectedActionId: "FUSION_BROWSER_OPEN",
    },
    {
      id: "combat-fusion-material-1",
      title: "Material 1",
      description: "Selecciona el primer material de fusión (ChatGPT o Gemini).",
      targetId: "tutorial-board-fusion-material-entity-chatgpt",
      allowedTargetIds: ["tutorial-board-fusion-browser", "tutorial-board-fusion-material-entity-chatgpt", "tutorial-board-fusion-material-entity-gemini"],
      completionType: "USER_ACTION",
      expectedActionId: "FUSION_MATERIAL_1_SELECTED",
    },
    {
      id: "combat-fusion-material-2",
      title: "Material 2",
      description: "Ahora selecciona el segundo material para completar la fusión.",
      targetId: "tutorial-board-fusion-material-entity-gemini",
      allowedTargetIds: ["tutorial-board-fusion-browser", "tutorial-board-fusion-material-entity-chatgpt", "tutorial-board-fusion-material-entity-gemini"],
      completionType: "USER_ACTION",
      expectedActionId: "FUSION_MATERIAL_2_SELECTED",
    },
    {
      id: "combat-fusion-summon-animation",
      title: "Invocación de fusión",
      description: "Perfecto. Ahora se ejecuta la animación y aparece GemGPT en el campo.",
      targetId: "tutorial-board-battlefield",
      allowedTargetIds: [],
      completionType: "USER_ACTION",
      expectedActionId: "FUSION_SUMMON",
    },
    {
      id: "combat-fusion-battle-phase",
      title: "Fase de Combate",
      description: "Ahora pulsa Combate para atacar con tu carta de fusión.",
      targetId: "tutorial-board-phase-battle-button",
      allowedTargetIds: ["tutorial-board-phase-controls", "tutorial-board-phase-battle-button"],
      completionType: "USER_ACTION",
      expectedActionId: "TURN_TO_BATTLE_AFTER_FUSION",
    },
    {
      id: "combat-fusion-direct-attack",
      title: "Ataque de GemGPT",
      description: "Ataca directo con GemGPT y después pulsa Pasar para ceder turno.",
      targetId: "tutorial-board-battlefield",
      allowedTargetIds: ["tutorial-board-battlefield", "tutorial-board-phase-controls", "tutorial-board-phase-pass-button"],
      completionType: "USER_ACTION",
      expectedActionId: "OPPONENT_DEFENSE_READY",
    },
    {
      id: "combat-select-python",
      title: "Robo de Python",
      description: "En tu siguiente turno roba y selecciona Python para mostrar ataque contra defensa.",
      targetId: "tutorial-board-hand-card-entity-python",
      allowedTargetIds: ["tutorial-board-hand-card-entity-python"],
      completionType: "USER_ACTION",
      expectedActionId: "SELECT_PYTHON",
    },
    {
      id: "combat-summon-python",
      title: "Invoca Python",
      description: "Invoca Python en ataque para preparar la secuencia final.",
      targetId: "tutorial-board-action-attack",
      allowedTargetIds: ["tutorial-board-action-attack", "tutorial-board-hand-card-entity-python"],
      completionType: "USER_ACTION",
      expectedActionId: "SUMMON_PYTHON_ATTACK",
    },
    {
      id: "combat-python-battle-phase",
      title: "Entrar en Combate",
      description: "Pulsa Combate para resolver ataque a carta en defensa y cierre del duelo.",
      targetId: "tutorial-board-phase-battle-button",
      allowedTargetIds: ["tutorial-board-phase-controls", "tutorial-board-phase-battle-button"],
      completionType: "USER_ACTION",
      expectedActionId: "TURN_TO_BATTLE_PYTHON",
    },
    {
      id: "combat-defense-attack-example",
      title: "Ataque a defensa y cierre",
      description: "Ataca con Python a la carta en defensa y cierra el duelo con ataque directo de GemGPT.",
      targetId: "tutorial-board-battlefield",
      allowedTargetIds: ["tutorial-board-battlefield"],
      completionType: "BOTH",
      expectedActionId: "MATCH_WON",
    },
  ];
}
