// src/components/game/board/board-test-fixtures.ts - Fixtures y mocks reutilizables para pruebas del componente Board.
import { vi } from "vitest";
import { IPlayer } from "@/core/entities/IPlayer";
import { ICard } from "@/core/entities/ICard";
import { GameState } from "@/core/use-cases/GameEngine";
import * as useBoardModule from "@/components/game/board/hooks/useBoard";

export const boardMockEntity: ICard = {
  id: "c1",
  name: "Hack Script",
  description: "Ataca fuerte",
  type: "ENTITY",
  faction: "OPEN_SOURCE",
  cost: 2,
  attack: 1500,
  defense: 1000,
};

export const boardMockPlayer: IPlayer = {
  id: "p1",
  name: "Boby Master",
  healthPoints: 4000,
  maxHealthPoints: 4000,
  currentEnergy: 5,
  maxEnergy: 10,
  deck: [],
  hand: [boardMockEntity],
  graveyard: [],
  activeEntities: [],
  activeExecutions: [],
};

export const boardMockOpponent: IPlayer = {
  id: "p2",
  name: "AI Overlord",
  healthPoints: 3500,
  maxHealthPoints: 4000,
  currentEnergy: 8,
  maxEnergy: 10,
  deck: [],
  hand: [],
  graveyard: [],
  activeEntities: [],
  activeExecutions: [],
};

export const boardMockGameState: GameState = {
  playerA: boardMockPlayer,
  playerB: boardMockOpponent,
  activePlayerId: "p1",
  startingPlayerId: "p1",
  turn: 1,
  phase: "MAIN_1",
  hasNormalSummonedThisTurn: false,
  pendingTurnAction: null,
  combatLog: [],
};

export function mockDefaultUseBoardReturn() {
  vi.mocked(useBoardModule.useBoard).mockReturnValue({
    gameState: boardMockGameState,
    selectedCard: null,
    selectedBoardEntityInstanceId: null,
    playingCard: null,
    isHistoryOpen: false,
    activeAttackerId: null,
    revealedEntities: [],
    lastError: null,
    pendingEntityReplacement: null,
    pendingEntityReplacementTargetId: null,
    pendingActionHint: null,
    pendingDiscardCardIds: [],
    pendingEntitySelectionIds: [],
    pendingFusionSelectedEntityIds: [],
    opponentDifficulty: "EASY",
    isPlayerTurn: true,
    isMuted: false,
    isPaused: false,
    isAutoPhaseEnabled: true,
    isTurnHelpEnabled: true,
    isFusionCinematicActive: false,
    lastDamageTargetPlayerId: null,
    lastDamageAmount: null,
    lastDamageEventId: null,
    lastHealTargetPlayerId: null,
    lastHealAmount: null,
    lastHealEventId: null,
    lastBuffTargetEntityIds: [],
    lastBuffStat: null,
    lastBuffAmount: null,
    lastBuffEventId: null,
    lastCardXpCardId: null,
    lastCardXpAmount: null,
    lastCardXpEventId: null,
    lastCardXpActorPlayerId: null,
    winnerPlayerId: null,
    resolvePendingTurnAction: vi.fn(),
    resolvePendingHandDiscard: vi.fn(),
    setIsHistoryOpen: vi.fn(),
    toggleCardSelection: vi.fn(),
    previewCard: vi.fn(),
    clearSelection: vi.fn(),
    clearError: vi.fn(),
    executePlayAction: vi.fn(),
    handleEntityClick: vi.fn(),
    advancePhase: vi.fn(),
    confirmAdvancePhase: vi.fn(),
    cancelAdvancePhase: vi.fn(),
    pendingAdvanceWarning: null,
    handleTimerExpired: vi.fn(),
    confirmEntityReplacement: vi.fn(),
    cancelEntityReplacement: vi.fn(),
    restartMatch: vi.fn(),
    toggleMute: vi.fn(),
    togglePause: vi.fn(),
    toggleAutoPhase: vi.fn(),
    setIsFusionCinematicActive: vi.fn(),
    setSelectedEntityToAttack: vi.fn(),
    canSetSelectedEntityToAttack: false,
    activateSelectedExecution: vi.fn(),
    canActivateSelectedExecution: false,
    battleExperienceSummary: [],
    battleExperienceCardLookup: {},
    isBattleExperiencePending: false,
    matchSeed: "test-seed",
    playTimerExpired: vi.fn(),
    playTimerWarning: vi.fn(),
    playButtonClick: vi.fn(),
    playBanner: vi.fn(),
  });
}
