// src/components/admin/internal/admin-story-deck-editor-types.ts - Tipos públicos del hook de edición Story Deck en panel admin.
import { IAdminStoryDeckApiResponse } from "@/components/admin/admin-story-deck-api";
import { IStorySlotLevelDraft } from "@/components/admin/internal/admin-story-duel-draft";
import { StoryAiStyle } from "@/core/services/opponent/difficulty/story-ai-profile";
import { StoryOpponentDifficulty } from "@/core/entities/opponent/IStoryDuelDefinition";

export interface IUseAdminStoryDeckEditorResult {
  data: IAdminStoryDeckApiResponse;
  selectedOpponentId: string | null;
  selectedSlotIndex: number | null;
  setSelectedSlotIndex: (slotIndex: number | null) => void;
  selectedCollectionCardId: string | null;
  setSelectedCollectionCardId: (cardId: string | null) => void;
  draftCardIds: Array<string | null>;
  selectedDuelId: string | null;
  setSelectedDuelId: (duelId: string | null) => void;
  selectedDuelDifficulty: StoryOpponentDifficulty;
  setSelectedDuelDifficulty: (difficulty: StoryOpponentDifficulty) => void;
  duelAiStyle: StoryAiStyle;
  setDuelAiStyle: (value: StoryAiStyle) => void;
  duelAiAggression: number;
  setDuelAiAggression: (value: number) => void;
  draftFusionCardIds: string[];
  setDraftFusionCardIdBySlot: (slotIndex: number, cardId: string) => void;
  clearDraftFusionCardBySlot: (slotIndex: number) => void;
  swapDraftFusionCards: (fromSlotIndex: number, toSlotIndex: number) => void;
  draftRewardCardIds: string[];
  setDraftRewardCardId: (cardId: string | null) => void;
  clearDraftRewardCard: () => void;
  draftSlotLevels: IStorySlotLevelDraft[];
  setDraftSlotLevelByIndex: (slotIndex: number, key: "versionTier" | "level" | "xp", value: number) => void;
  applyMassSlotLevels: (input: { versionTier: number; level: number; xp: number }) => void;
  setDraftCardIdBySlot: (slotIndex: number, cardId: string) => void;
  clearSlotCardByIndex: (slotIndex: number) => void;
  swapSlots: (fromSlotIndex: number, toSlotIndex: number) => void;
  isEditMode: boolean;
  setIsEditMode: (value: boolean) => void;
  isBaseDeckMode: boolean;
  setIsBaseDeckMode: (value: boolean) => void;
  isBusy: boolean;
  feedback: string;
  setFeedbackMessage: (message: string) => void;
  canSave: boolean;
  onSelectOpponent: (opponentId: string) => Promise<void>;
  onSelectDuelReference: (duelId: string) => Promise<void>;
  cloneFromDuel: (duelId: string) => void;
  onSelectDeck: (deckListId: string) => Promise<void>;
  onRefresh: () => Promise<void>;
  onSave: () => Promise<void>;
}
