// src/components/admin/internal/AdminCardCatalogFormFields.tsx - Renderiza formulario guiado del catálogo con labels, ejemplos y auto-plantillas por tipo.
"use client";

import { IAdminCardCatalogDraft } from "@/components/admin/internal/admin-card-catalog-draft";
import { CardType } from "@/core/entities/ICard";

interface IAdminCardCatalogFormFieldsProps {
  draft: IAdminCardCatalogDraft;
  isBusy: boolean;
  onChange: <K extends keyof IAdminCardCatalogDraft>(key: K, value: IAdminCardCatalogDraft[K]) => void;
  onApplyTypeTemplate: (nextType: CardType, force: boolean) => void;
}

export function AdminCardCatalogFormFields({ draft, isBusy, onChange, onApplyTypeTemplate }: IAdminCardCatalogFormFieldsProps) {
  return <div className="home-modern-scroll min-h-0 space-y-4 overflow-y-auto pr-2">
    <section className="space-y-2 rounded-lg border border-slate-700/80 bg-slate-950/40 p-3">
      <div className="flex items-center justify-between"><p className="text-[11px] font-bold uppercase tracking-wide text-cyan-200">Identidad</p><button type="button" aria-label="Rellenar ejemplo según tipo" className="h-7 rounded-md border border-cyan-500 px-2 text-[11px] font-bold uppercase text-cyan-200" onClick={() => onApplyTypeTemplate(draft.type, true)} disabled={isBusy}>Rellenar Ejemplo</button></div>
      <div className="grid gap-2 md:grid-cols-2"><label className="text-[11px] text-slate-300">ID de carta<input aria-label="ID de carta" className="mt-1 w-full rounded-md border border-slate-600 bg-slate-900 p-2 text-xs text-slate-100" value={draft.id} onChange={(event) => onChange("id", event.target.value)} placeholder="entity-vscode | trap-counter" disabled={isBusy} /></label><label className="text-[11px] text-slate-300">Nombre visible<input aria-label="Nombre de carta" className="mt-1 w-full rounded-md border border-slate-600 bg-slate-900 p-2 text-xs text-slate-100" value={draft.name} onChange={(event) => onChange("name", event.target.value)} placeholder="VSCODE | Counter Intrusion" disabled={isBusy} /></label></div>
      <label className="text-[11px] text-slate-300">Descripción<input aria-label="Descripción de carta" className="mt-1 w-full rounded-md border border-slate-600 bg-slate-900 p-2 text-xs text-slate-100" value={draft.description} onChange={(event) => onChange("description", event.target.value)} placeholder="Texto corto para explicar el efecto." disabled={isBusy} /></label>
    </section>

    <section className="space-y-2 rounded-lg border border-slate-700/80 bg-slate-950/40 p-3">
      <p className="text-[11px] font-bold uppercase tracking-wide text-cyan-200">Atributos base</p>
      <div className="grid gap-2 md:grid-cols-4"><label className="text-[11px] text-slate-300">Tipo<select aria-label="Tipo de carta" className="mt-1 w-full rounded-md border border-slate-600 bg-slate-900 p-2 text-xs text-slate-100" value={draft.type} onChange={(event) => { const nextType = event.target.value as CardType; onChange("type", nextType as IAdminCardCatalogDraft["type"]); onApplyTypeTemplate(nextType, true); }} disabled={isBusy}><option value="ENTITY">Entity</option><option value="EXECUTION">Execution</option><option value="TRAP">Trap</option><option value="FUSION">Fusion</option><option value="ENVIRONMENT">Environment</option></select></label><label className="text-[11px] text-slate-300">Facción<select aria-label="Facción de carta" className="mt-1 w-full rounded-md border border-slate-600 bg-slate-900 p-2 text-xs text-slate-100" value={draft.faction} onChange={(event) => onChange("faction", event.target.value as IAdminCardCatalogDraft["faction"])} disabled={isBusy}><option value="NEUTRAL">Neutral</option><option value="OPEN_SOURCE">Open Source</option><option value="BIG_TECH">Big Tech</option><option value="NO_CODE">No Code</option></select></label><label className="text-[11px] text-slate-300">Coste<input aria-label="Coste" className="mt-1 w-full rounded-md border border-slate-600 bg-slate-900 p-2 text-xs text-slate-100" value={draft.costText} onChange={(event) => onChange("costText", event.target.value)} placeholder="Ej: 3" disabled={isBusy} /></label><label className="inline-flex items-center gap-2 self-end rounded-md border border-slate-600 bg-slate-900 p-2 text-xs text-slate-100"><input type="checkbox" checked={draft.isActive} onChange={(event) => onChange("isActive", event.target.checked)} disabled={isBusy} />Activa</label></div>
      <div className="grid gap-2 md:grid-cols-2"><label className="text-[11px] text-slate-300">Ataque (solo ENTITY/FUSION)<input aria-label="Ataque" className="mt-1 w-full rounded-md border border-slate-600 bg-slate-900 p-2 text-xs text-slate-100" value={draft.attackText} onChange={(event) => onChange("attackText", event.target.value)} placeholder="Ej: 1200" disabled={isBusy} /></label><label className="text-[11px] text-slate-300">Defensa (solo ENTITY/FUSION)<input aria-label="Defensa" className="mt-1 w-full rounded-md border border-slate-600 bg-slate-900 p-2 text-xs text-slate-100" value={draft.defenseText} onChange={(event) => onChange("defenseText", event.target.value)} placeholder="Ej: 1000" disabled={isBusy} /></label></div>
    </section>

    <section className="space-y-2 rounded-lg border border-slate-700/80 bg-slate-950/40 p-3">
      <p className="text-[11px] font-bold uppercase tracking-wide text-cyan-200">Afinidad y trigger</p>
      <div className="grid gap-2 md:grid-cols-2"><label className="text-[11px] text-slate-300">Arquetipo<select aria-label="Arquetipo" className="mt-1 w-full rounded-md border border-slate-600 bg-slate-900 p-2 text-xs text-slate-100" value={draft.archetype} onChange={(event) => onChange("archetype", event.target.value as IAdminCardCatalogDraft["archetype"])} disabled={isBusy}><option value="NONE">Sin arquetipo</option><option value="LLM">LLM</option><option value="FRAMEWORK">Framework</option><option value="DB">DB</option><option value="IDE">IDE</option><option value="LANGUAGE">Language</option><option value="TOOL">Tool</option><option value="SECURITY">Security</option></select></label><label className="text-[11px] text-slate-300">Trigger (solo TRAP)<select aria-label="Trigger de trampa" className="mt-1 w-full rounded-md border border-slate-600 bg-slate-900 p-2 text-xs text-slate-100" value={draft.trigger} onChange={(event) => onChange("trigger", event.target.value as IAdminCardCatalogDraft["trigger"])} disabled={isBusy}><option value="NONE">Sin trigger</option><option value="ON_OPPONENT_ATTACK_DECLARED">On Opponent Attack Declared</option><option value="ON_OPPONENT_EXECUTION_ACTIVATED">On Opponent Execution Activated</option><option value="ON_OPPONENT_TRAP_ACTIVATED">On Opponent Trap Activated</option><option value="ON_OPPONENT_STAT_BUFF_APPLIED">On Opponent Stat Buff Applied</option><option value="ON_OPPONENT_ENTITY_SET_PLAYED">On Opponent Entity Set Played</option><option value="ON_OPPONENT_DIRECT_ATTACK_DECLARED">On Opponent Direct Attack Declared</option></select></label></div>
    </section>

    <section className="space-y-2 rounded-lg border border-slate-700/80 bg-slate-950/40 p-3">
      <p className="text-[11px] font-bold uppercase tracking-wide text-cyan-200">Arte y fusión</p>
      <div className="grid gap-2 md:grid-cols-2"><label className="text-[11px] text-slate-300">Render URL<input aria-label="URL de render" className="mt-1 w-full rounded-md border border-slate-600 bg-slate-900 p-2 text-xs text-slate-100" value={draft.renderUrl} onChange={(event) => onChange("renderUrl", event.target.value)} placeholder="/assets/renders/*/*.webp" disabled={isBusy} /></label><label className="text-[11px] text-slate-300">Background URL (auto por tipo)<input aria-label="URL de fondo" readOnly className="mt-1 w-full rounded-md border border-slate-600 bg-slate-900/70 p-2 text-xs text-cyan-100" value={draft.bgUrl} placeholder="Vacío en TRAP/EXECUTION" /></label></div>
      <div className="grid gap-2 md:grid-cols-3"><label className="text-[11px] text-slate-300">Fusion recipe id<input aria-label="Fusion recipe id" className="mt-1 w-full rounded-md border border-slate-600 bg-slate-900 p-2 text-xs text-slate-100" value={draft.fusionRecipeId} onChange={(event) => onChange("fusionRecipeId", event.target.value)} placeholder="fusion-recipe-example" disabled={isBusy} /></label><label className="text-[11px] text-slate-300">Fusion materials<input aria-label="Fusion materials" className="mt-1 w-full rounded-md border border-slate-600 bg-slate-900 p-2 text-xs text-slate-100" value={draft.fusionMaterialIdsText} onChange={(event) => onChange("fusionMaterialIdsText", event.target.value)} placeholder="entity-a,entity-b" disabled={isBusy} /></label><label className="text-[11px] text-slate-300">Energía de fusión<input aria-label="Energía de fusión" className="mt-1 w-full rounded-md border border-slate-600 bg-slate-900 p-2 text-xs text-slate-100" value={draft.fusionEnergyRequirementText} onChange={(event) => onChange("fusionEnergyRequirementText", event.target.value)} placeholder="Ej: 2" disabled={isBusy} /></label></div>
    </section>

    <section className="space-y-2 rounded-lg border border-slate-700/80 bg-slate-950/40 p-3"><p className="text-[11px] font-bold uppercase tracking-wide text-cyan-200">Lógica (effect JSON)</p><label className="text-[11px] text-slate-300">JSON del efecto<textarea aria-label="JSON de efecto" className="mt-1 min-h-28 w-full rounded-md border border-slate-600 bg-slate-900 p-2 font-mono text-xs text-slate-100" value={draft.effectJson} onChange={(event) => onChange("effectJson", event.target.value)} placeholder='{"action":"DAMAGE","target":"OPPONENT","value":300}' disabled={isBusy} /></label></section>
  </div>;
}
