-- docs/supabase/sql/005_seed_extra_cards_and_market.sql - Inserta cartas extra (entidades, mágicas y trampas) y sus listados de mercado en Nexus.
begin;

insert into public.cards_catalog (
  id, name, description, type, faction, cost, attack, defense, archetype, trigger, bg_url, render_url, effect, fusion_recipe_id, fusion_material_ids, fusion_energy_requirement, is_active
) values
('exec-antigrabity', 'Antigravity Pulse', 'Distorsiona el campo y fortalece tu defensa.', 'EXECUTION', 'NO_CODE', 3, null, null, null, null, '/assets/bgs/bg-tech.jpg', '/assets/renders/antigrabity.png', '{"action":"BOOST_DEFENSE_BY_ARCHETYPE","archetype":"TOOL","value":300}'::jsonb, null, '{}', null, true),
('entity-apple', 'Apple', 'Ecosistema premium con control de ritmo.', 'ENTITY', 'BIG_TECH', 5, 1830, 1390, 'TOOL', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/apple.png', null, null, '{}', null, true),
('entity-brave', 'Brave', 'Navegador táctico con enfoque en privacidad.', 'ENTITY', 'OPEN_SOURCE', 3, 1210, 1120, 'TOOL', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/brave.png', null, null, '{}', null, true),
('entity-csharp', 'C#', 'Lenguaje de alto rendimiento para combos sólidos.', 'ENTITY', 'BIG_TECH', 4, 1520, 1180, 'LANGUAGE', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/c%23.png', null, null, '{}', null, true),
('entity-cpp', 'C++', 'Compilación extrema para jugadas de precisión.', 'ENTITY', 'OPEN_SOURCE', 5, 1890, 1310, 'LANGUAGE', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/c%2B%2B.png', null, null, '{}', null, true),
('entity-chrome', 'Chrome', 'Dominio de navegación con presión constante.', 'ENTITY', 'BIG_TECH', 4, 1560, 1110, 'TOOL', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/chrome.png', null, null, '{}', null, true),
('entity-cloudflare', 'Cloudflare', 'Muralla de red que mitiga daño explosivo.', 'ENTITY', 'BIG_TECH', 4, 1480, 1240, 'SECURITY', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/cloudflare.png', null, null, '{}', null, true),
('entity-digitalocean', 'DigitalOcean', 'Infraestructura flexible para juego medio.', 'ENTITY', 'OPEN_SOURCE', 3, 1240, 1090, 'TOOL', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/digitalocean%20.png', null, null, '{}', null, true),
('exec-discord-sync', 'Discord Sync', 'Coordina al escuadrón e inflige daño directo.', 'EXECUTION', 'NO_CODE', 2, null, null, null, null, '/assets/bgs/bg-tech.jpg', '/assets/renders/discord.png', '{"action":"DAMAGE","target":"OPPONENT","value":600}'::jsonb, null, '{}', null, true),
('entity-docker', 'Docker', 'Conteneriza recursos y estabiliza la mesa.', 'ENTITY', 'OPEN_SOURCE', 4, 1490, 1200, 'TOOL', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/docker.png', null, null, '{}', null, true),
('exec-duckduckgo-scan', 'DuckDuckGo Scan', 'Escaneo ágil: roba 1 carta.', 'EXECUTION', 'NO_CODE', 2, null, null, null, null, '/assets/bgs/bg-tech.jpg', '/assets/renders/duckduckgo.png', '{"action":"DRAW_CARD","cards":1}'::jsonb, null, '{}', null, true),
('entity-edge', 'Edge', 'Cliente optimizado para presión incremental.', 'ENTITY', 'BIG_TECH', 3, 1260, 1080, 'TOOL', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/edge.png', null, null, '{}', null, true),
('entity-firefox', 'Firefox', 'Navegador veloz con espíritu libre.', 'ENTITY', 'OPEN_SOURCE', 3, 1230, 1130, 'TOOL', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/firefox.png', null, null, '{}', null, true),
('entity-hostinger', 'Hostinger', 'Hosting ligero para jugadas de tempo.', 'ENTITY', 'NO_CODE', 3, 1250, 1070, 'TOOL', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/hostinger.png', null, null, '{}', null, true),
('trap-hydra-counter', 'Hydra Countermeasure', 'Al declarar ataque rival, castiga con daño directo.', 'TRAP', 'OPEN_SOURCE', 2, null, null, null, 'ON_OPPONENT_ATTACK_DECLARED', '/assets/bgs/bg-tech.jpg', '/assets/renders/hydra.png', '{"action":"DAMAGE","target":"OPPONENT","value":500}'::jsonb, null, '{}', null, true),
('entity-ai-prototype-33', 'AI Prototype 33', 'Prototipo experimental de soporte híbrido.', 'ENTITY', 'NEUTRAL', 4, 1510, 1140, 'LLM', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/image-removebg-preview%20%2833%29.png', null, null, '{}', null, true),
('entity-javascript', 'JavaScript', 'Lenguaje versátil para cadenas de efectos.', 'ENTITY', 'OPEN_SOURCE', 3, 1220, 1090, 'LANGUAGE', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/javascript.png', null, null, '{}', null, true),
('entity-kubernetes', 'Kubernetes', 'Orquestación robusta con defensa escalable.', 'ENTITY', 'OPEN_SOURCE', 5, 1860, 1410, 'TOOL', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/kubernetes.png', null, null, '{}', null, true),
('entity-linux', 'Linux', 'Kernel abierto con resistencia superior.', 'ENTITY', 'OPEN_SOURCE', 4, 1540, 1230, 'SECURITY', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/linux.png', null, null, '{}', null, true),
('entity-mariadb', 'MariaDB', 'Gestor relacional de defensa consistente.', 'ENTITY', 'OPEN_SOURCE', 4, 1470, 1260, 'DB', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/mariadb.png', null, null, '{}', null, true),
('entity-mongodb', 'MongoDB', 'Base documental agresiva en mid game.', 'ENTITY', 'OPEN_SOURCE', 4, 1530, 1150, 'DB', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/mongodb.png', null, null, '{}', null, true),
('entity-nexus', 'Nexus Core', 'Núcleo energético que estabiliza recursos.', 'ENTITY', 'NEUTRAL', 4, 1500, 1220, 'TOOL', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/nexus.png', null, null, '{}', null, true),
('exec-notebookllm-archive', 'NotebookLLM Archive', 'Consolida conocimiento y recupera LP.', 'EXECUTION', 'NO_CODE', 2, null, null, null, null, '/assets/bgs/bg-tech.jpg', '/assets/renders/notebookllm.png', '{"action":"HEAL","target":"PLAYER","value":700}'::jsonb, null, '{}', null, true),
('entity-nuxtjs', 'Nuxt.js', 'Framework full-stack de despliegue rápido.', 'ENTITY', 'OPEN_SOURCE', 4, 1500, 1120, 'FRAMEWORK', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/nuxtjs.png', null, null, '{}', null, true),
('entity-rust', 'Rust', 'Seguridad de memoria para finales sólidos.', 'ENTITY', 'OPEN_SOURCE', 5, 1900, 1340, 'LANGUAGE', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/rust.png', null, null, '{}', null, true),
('entity-safari', 'Safari', 'Navegación optimizada para control de mano.', 'ENTITY', 'BIG_TECH', 3, 1200, 1140, 'TOOL', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/safari.png', null, null, '{}', null, true),
('entity-sqlite', 'SQLite', 'Base embebida con defensa eficiente.', 'ENTITY', 'OPEN_SOURCE', 3, 1210, 1160, 'DB', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/sqlite.png', null, null, '{}', null, true),
('entity-strapi', 'Strapi', 'CMS desacoplado de respuesta rápida.', 'ENTITY', 'OPEN_SOURCE', 3, 1240, 1100, 'TOOL', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/strapi.png', null, null, '{}', null, true),
('entity-svelte', 'Svelte', 'Framework liviano para ataques de tempo.', 'ENTITY', 'OPEN_SOURCE', 3, 1270, 1060, 'FRAMEWORK', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/svelte.png', null, null, '{}', null, true),
('trap-tor-smokescreen', 'Tor Smokescreen', 'Al activar ejecución rival, debilita su ataque.', 'TRAP', 'OPEN_SOURCE', 2, null, null, null, 'ON_OPPONENT_EXECUTION_ACTIVATED', '/assets/bgs/bg-tech.jpg', '/assets/renders/tor.png', '{"action":"REDUCE_OPPONENT_ATTACK","value":300}'::jsonb, null, '{}', null, true),
('entity-typescript', 'TypeScript', 'Tipado estricto para duelos consistentes.', 'ENTITY', 'OPEN_SOURCE', 4, 1540, 1170, 'LANGUAGE', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/typescript.png', null, null, '{}', null, true),
('entity-unity', 'Unity', 'Motor interactivo de presión sostenida.', 'ENTITY', 'BIG_TECH', 4, 1520, 1130, 'FRAMEWORK', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/unity.png', null, null, '{}', null, true),
('entity-vue', 'Vue', 'Framework progresivo de ataque estable.', 'ENTITY', 'OPEN_SOURCE', 4, 1510, 1140, 'FRAMEWORK', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/vue.png', null, null, '{}', null, true),
('entity-windows11', 'Windows 11', 'Sistema de control con buena defensa base.', 'ENTITY', 'BIG_TECH', 4, 1490, 1210, 'TOOL', null, '/assets/bgs/bg-tech.jpg', '/assets/renders/windows11.png', null, null, '{}', null, true),
('trap-windows92-crash', 'Windows 92 Crash', 'Niega el ataque rival y destruye al atacante.', 'TRAP', 'NEUTRAL', 3, null, null, null, 'ON_OPPONENT_ATTACK_DECLARED', '/assets/bgs/bg-tech.jpg', '/assets/renders/windows92.png', '{"action":"NEGATE_ATTACK_AND_DESTROY_ATTACKER"}'::jsonb, null, '{}', null, true),
('exec-wrap-overclock', 'WRAP Overclock', 'Refuerza las entidades de framework.', 'EXECUTION', 'NO_CODE', 3, null, null, null, null, '/assets/bgs/bg-tech.jpg', '/assets/renders/wrap.png', '{"action":"BOOST_ATTACK_BY_ARCHETYPE","archetype":"FRAMEWORK","value":300}'::jsonb, null, '{}', null, true)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  type = excluded.type,
  faction = excluded.faction,
  cost = excluded.cost,
  attack = excluded.attack,
  defense = excluded.defense,
  archetype = excluded.archetype,
  trigger = excluded.trigger,
  bg_url = excluded.bg_url,
  render_url = excluded.render_url,
  effect = excluded.effect,
  fusion_recipe_id = excluded.fusion_recipe_id,
  fusion_material_ids = excluded.fusion_material_ids,
  fusion_energy_requirement = excluded.fusion_energy_requirement,
  is_active = excluded.is_active;

insert into public.market_card_listings (id, card_id, rarity, price_nexus, stock, is_available) values
('listing-exec-antigrabity', 'exec-antigrabity', 'RARE', 100, null, true),
('listing-entity-apple', 'entity-apple', 'EPIC', 130, null, true),
('listing-entity-brave', 'entity-brave', 'COMMON', 75, null, true),
('listing-entity-csharp', 'entity-csharp', 'RARE', 100, null, true),
('listing-entity-cpp', 'entity-cpp', 'EPIC', 125, null, true),
('listing-entity-chrome', 'entity-chrome', 'RARE', 100, null, true),
('listing-entity-cloudflare', 'entity-cloudflare', 'RARE', 100, null, true),
('listing-entity-digitalocean', 'entity-digitalocean', 'COMMON', 75, null, true),
('listing-exec-discord-sync', 'exec-discord-sync', 'COMMON', 50, null, true),
('listing-entity-docker', 'entity-docker', 'RARE', 100, null, true),
('listing-exec-duckduckgo-scan', 'exec-duckduckgo-scan', 'COMMON', 50, null, true),
('listing-entity-edge', 'entity-edge', 'COMMON', 75, null, true),
('listing-entity-firefox', 'entity-firefox', 'COMMON', 75, null, true),
('listing-entity-hostinger', 'entity-hostinger', 'COMMON', 75, null, true),
('listing-trap-hydra-counter', 'trap-hydra-counter', 'COMMON', 50, null, true),
('listing-entity-ai-prototype-33', 'entity-ai-prototype-33', 'EPIC', 125, null, true),
('listing-entity-javascript', 'entity-javascript', 'RARE', 100, null, true),
('listing-entity-kubernetes', 'entity-kubernetes', 'EPIC', 125, null, true),
('listing-entity-linux', 'entity-linux', 'RARE', 100, null, true),
('listing-entity-mariadb', 'entity-mariadb', 'RARE', 100, null, true),
('listing-entity-mongodb', 'entity-mongodb', 'RARE', 100, null, true),
('listing-entity-nexus', 'entity-nexus', 'RARE', 100, null, true),
('listing-exec-notebookllm-archive', 'exec-notebookllm-archive', 'COMMON', 50, null, true),
('listing-entity-nuxtjs', 'entity-nuxtjs', 'RARE', 100, null, true),
('listing-entity-rust', 'entity-rust', 'EPIC', 125, null, true),
('listing-entity-safari', 'entity-safari', 'COMMON', 75, null, true),
('listing-entity-sqlite', 'entity-sqlite', 'COMMON', 75, null, true),
('listing-entity-strapi', 'entity-strapi', 'COMMON', 75, null, true),
('listing-entity-svelte', 'entity-svelte', 'COMMON', 75, null, true),
('listing-trap-tor-smokescreen', 'trap-tor-smokescreen', 'COMMON', 50, null, true),
('listing-entity-typescript', 'entity-typescript', 'RARE', 100, null, true),
('listing-entity-unity', 'entity-unity', 'RARE', 100, null, true),
('listing-entity-vue', 'entity-vue', 'RARE', 100, null, true),
('listing-entity-windows11', 'entity-windows11', 'RARE', 100, null, true),
('listing-trap-windows92-crash', 'trap-windows92-crash', 'RARE', 100, null, true),
('listing-exec-wrap-overclock', 'exec-wrap-overclock', 'RARE', 100, null, true)
on conflict (id) do update set
  card_id = excluded.card_id,
  rarity = excluded.rarity,
  price_nexus = excluded.price_nexus,
  stock = excluded.stock,
  is_available = excluded.is_available;

commit;
