-- docs/supabase/sql/029_phase_cards_add_new_render_entities.sql - Registra nuevas entidades del pool render (Avast, Figma, Flutter, Kotlin y Unreal Engine) con balance base y listing de mercado.
begin;

insert into public.cards_catalog (
  id,
  name,
  description,
  type,
  faction,
  cost,
  attack,
  defense,
  archetype,
  trigger,
  bg_url,
  render_url,
  effect,
  fusion_recipe_id,
  fusion_material_ids,
  fusion_energy_requirement,
  is_active
) values
(
  'entity-avast',
  'Avast',
  'Escudo antivirus que absorbe presión inicial y estabiliza la línea defensiva.',
  'ENTITY',
  'BIG_TECH',
  4,
  1460,
  1320,
  'SECURITY',
  null,
  '/assets/bgs/bg-tech.jpg',
  '/assets/renders/avast.webp',
  null,
  null,
  '{}',
  null,
  true
),
(
  'entity-figma',
  'Figma',
  'Tablero colaborativo que optimiza jugadas de tempo y soporte.',
  'ENTITY',
  'NO_CODE',
  3,
  1240,
  1120,
  'TOOL',
  null,
  '/assets/bgs/bg-tech.jpg',
  '/assets/renders/figma.webp',
  null,
  null,
  '{}',
  null,
  true
),
(
  'entity-flutter',
  'Flutter',
  'Framework cross-platform que acelera despliegues y presión de medio juego.',
  'ENTITY',
  'OPEN_SOURCE',
  4,
  1570,
  1130,
  'FRAMEWORK',
  null,
  '/assets/bgs/bg-tech.jpg',
  '/assets/renders/flutter.webp',
  null,
  null,
  '{}',
  null,
  true
),
(
  'entity-kotlin',
  'Kotlin',
  'Lenguaje moderno con ejecución estable para cadenas técnicas consistentes.',
  'ENTITY',
  'OPEN_SOURCE',
  4,
  1560,
  1160,
  'LANGUAGE',
  null,
  '/assets/bgs/bg-tech.jpg',
  '/assets/renders/kotlin.webp',
  null,
  null,
  '{}',
  null,
  true
),
(
  'entity-unreal-engine',
  'Unreal Engine',
  'Motor de alto impacto visual que domina cierres con potencia bruta.',
  'ENTITY',
  'BIG_TECH',
  5,
  1880,
  1280,
  'FRAMEWORK',
  null,
  '/assets/bgs/bg-tech.jpg',
  '/assets/renders/unreal-engine.webp',
  null,
  null,
  '{}',
  null,
  true
)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  type = excluded.type,
  faction = excluded.faction,
  cost = excluded.cost,
  attack = excluded.attack,
  defense = excluded.defense,
  archetype = excluded.archetype,
  trigger = excluded.trigger,
  bg_url = excluded.bg_url,
  render_url = excluded.render_url,
  effect = excluded.effect,
  fusion_recipe_id = excluded.fusion_recipe_id,
  fusion_material_ids = excluded.fusion_material_ids,
  fusion_energy_requirement = excluded.fusion_energy_requirement,
  is_active = excluded.is_active;

insert into public.market_card_listings (
  id,
  card_id,
  rarity,
  price_nexus,
  stock,
  is_available
) values
('listing-entity-avast', 'entity-avast', 'RARE', 110, null, true),
('listing-entity-figma', 'entity-figma', 'COMMON', 85, null, true),
('listing-entity-flutter', 'entity-flutter', 'RARE', 118, null, true),
('listing-entity-kotlin', 'entity-kotlin', 'RARE', 116, null, true),
('listing-entity-unreal-engine', 'entity-unreal-engine', 'EPIC', 135, null, true)
on conflict (id) do update set
  card_id = excluded.card_id,
  rarity = excluded.rarity,
  price_nexus = excluded.price_nexus,
  stock = excluded.stock,
  is_available = excluded.is_available;

commit;
