-- docs/supabase/sql/030_phase_new_effect_cards_phase2.sql - Extiende triggers de trampa y registra cartas nuevas de Fase 2 con efectos avanzados de combate.
begin;

alter table public.cards_catalog
  drop constraint if exists cards_catalog_trigger_check;

alter table public.cards_catalog
  add constraint cards_catalog_trigger_check
  check (
    trigger is null
    or trigger in (
      'ON_OPPONENT_ATTACK_DECLARED',
      'ON_OPPONENT_EXECUTION_ACTIVATED',
      'ON_OPPONENT_TRAP_ACTIVATED',
      'ON_OPPONENT_STAT_BUFF_APPLIED',
      'ON_OPPONENT_ENTITY_SET_PLAYED',
      'ON_OPPONENT_DIRECT_ATTACK_DECLARED'
    )
  );

insert into public.cards_catalog (
  id,
  name,
  description,
  type,
  faction,
  cost,
  attack,
  defense,
  archetype,
  trigger,
  bg_url,
  render_url,
  effect,
  fusion_recipe_id,
  fusion_material_ids,
  fusion_energy_requirement,
  is_active
) values
(
  'trap-mirror-buff-injection',
  'Mirror Buff Injection',
  'Cuando el rival aplica un buff de stats, replica el mismo buff a todas tus entidades.',
  'TRAP',
  'OPEN_SOURCE',
  3,
  null,
  null,
  null,
  'ON_OPPONENT_STAT_BUFF_APPLIED',
  null,
  '/assets/renders/traps/trap-mirror-buff-injection.webp',
  '{"action":"COPY_OPPONENT_BUFF_TO_ALLIED_ENTITIES"}'::jsonb,
  null,
  '{}',
  null,
  true
),
(
  'trap-force-overclock-lock',
  'Force Overclock Lock',
  'Si el rival invoca una entidad en defensa, la fuerza a ataque y bloquea su modo hasta que sea destruida.',
  'TRAP',
  'BIG_TECH',
  2,
  null,
  null,
  null,
  'ON_OPPONENT_ENTITY_SET_PLAYED',
  null,
  '/assets/renders/traps/trap-force-overclock-lock.webp',
  '{"action":"FORCE_SUMMONED_DEFENSE_TO_ATTACK_LOCKED"}'::jsonb,
  null,
  '{}',
  null,
  true
),
(
  'trap-nexus-reset-barrier',
  'Nexus Reset Barrier',
  'Al declarar ataque directo rival, drena su energía a 0 y fija tu energía en 10.',
  'TRAP',
  'NO_CODE',
  3,
  null,
  null,
  null,
  'ON_OPPONENT_DIRECT_ATTACK_DECLARED',
  null,
  '/assets/renders/traps/trap-nexus-reset-barrier.webp',
  '{"action":"DIRECT_ATTACK_ENERGY_DRAIN_AND_SET_SELF_TO_TEN"}'::jsonb,
  null,
  '{}',
  null,
  true
),
(
  'trap-nullify-opponent-trap',
  'Nullify Opponent Trap',
  'Cuando el rival activa una trampa, la niega y la destruye.',
  'TRAP',
  'NEUTRAL',
  2,
  null,
  null,
  null,
  'ON_OPPONENT_TRAP_ACTIVATED',
  null,
  '/assets/renders/traps/trap-nullify-opponent-trap.webp',
  '{"action":"NEGATE_OPPONENT_TRAP_AND_DESTROY"}'::jsonb,
  null,
  '{}',
  null,
  true
),
(
  'exec-docker-defense-1000',
  'Docker Defense Patch',
  'Fija la defensa de Docker a 1000 durante este duelo.',
  'EXECUTION',
  'OPEN_SOURCE',
  2,
  null,
  null,
  null,
  null,
  null,
  '/assets/renders/executions/exec-docker-defense-1000.webp',
  '{"action":"SET_DEFENSE_BY_CARD_ID","targetCardId":"entity-docker","value":1000}'::jsonb,
  null,
  '{}',
  null,
  true
),
(
  'exec-duckduckgo-power-up',
  'DuckDuckGo Power Upgrade',
  'Ajusta DuckDuckGo a versión 5 y nivel 5 durante este combate.',
  'EXECUTION',
  'NO_CODE',
  2,
  null,
  null,
  null,
  null,
  null,
  '/assets/renders/executions/exec-duckduckgo-power-up.webp',
  '{"action":"SET_CARD_DUEL_PROGRESS","targetCardId":"exec-duckduckgo-scan","level":5,"versionTier":5}'::jsonb,
  null,
  '{}',
  null,
  true
),
(
  'exec-drain-opponent-energy',
  'Energy Breach',
  'Drena toda la energía del rival.',
  'EXECUTION',
  'OPEN_SOURCE',
  3,
  null,
  null,
  null,
  null,
  null,
  '/assets/renders/executions/exec-drain-opponent-energy.webp',
  '{"action":"DRAIN_OPPONENT_ENERGY"}'::jsonb,
  null,
  '{}',
  null,
  true
),
(
  'exec-reveal-opponent-set-card',
  'Reveal Set Protocol',
  'Permite revelar una carta seteada del rival.',
  'EXECUTION',
  'NO_CODE',
  1,
  null,
  null,
  null,
  null,
  null,
  '/assets/renders/executions/exec-reveal-opponent-set-card.webp',
  '{"action":"REVEAL_OPPONENT_SET_CARD","zone":"ANY"}'::jsonb,
  null,
  '{}',
  null,
  true
),
(
  'exec-steal-opponent-graveyard-card',
  'Graveyard Hijack',
  'Permite robar una carta ENTITY del cementerio rival.',
  'EXECUTION',
  'OPEN_SOURCE',
  3,
  null,
  null,
  null,
  null,
  null,
  '/assets/renders/executions/exec-steal-opponent-graveyard-card.webp',
  '{"action":"STEAL_OPPONENT_GRAVEYARD_CARD_TO_HAND","cardType":"ENTITY"}'::jsonb,
  null,
  '{}',
  null,
  true
)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  type = excluded.type,
  faction = excluded.faction,
  cost = excluded.cost,
  attack = excluded.attack,
  defense = excluded.defense,
  archetype = excluded.archetype,
  trigger = excluded.trigger,
  bg_url = excluded.bg_url,
  render_url = excluded.render_url,
  effect = excluded.effect,
  fusion_recipe_id = excluded.fusion_recipe_id,
  fusion_material_ids = excluded.fusion_material_ids,
  fusion_energy_requirement = excluded.fusion_energy_requirement,
  is_active = excluded.is_active;

insert into public.market_card_listings (
  id,
  card_id,
  rarity,
  price_nexus,
  stock,
  is_available
) values
('listing-trap-mirror-buff-injection', 'trap-mirror-buff-injection', 'EPIC', 170, null, true),
('listing-trap-force-overclock-lock', 'trap-force-overclock-lock', 'RARE', 125, null, true),
('listing-trap-nexus-reset-barrier', 'trap-nexus-reset-barrier', 'EPIC', 190, null, true),
('listing-trap-nullify-opponent-trap', 'trap-nullify-opponent-trap', 'RARE', 130, null, true),
('listing-exec-docker-defense-1000', 'exec-docker-defense-1000', 'RARE', 120, null, true),
('listing-exec-duckduckgo-power-up', 'exec-duckduckgo-power-up', 'EPIC', 180, null, true),
('listing-exec-drain-opponent-energy', 'exec-drain-opponent-energy', 'EPIC', 190, null, true),
('listing-exec-reveal-opponent-set-card', 'exec-reveal-opponent-set-card', 'RARE', 110, null, true),
('listing-exec-steal-opponent-graveyard-card', 'exec-steal-opponent-graveyard-card', 'EPIC', 200, null, true)
on conflict (id) do update set
  card_id = excluded.card_id,
  rarity = excluded.rarity,
  price_nexus = excluded.price_nexus,
  stock = excluded.stock,
  is_available = excluded.is_available;

commit;
